name: Build Goo Engine (Windows)

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - goo-engine-v3.6-release

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Goo Engine
        uses: actions/checkout@v3
        with:
          ref: goo-engine-v3.6-release   # build this branch

      - name: Install dependencies
        run: |
          choco install -y cmake ninja git

      - name: Update libraries
        run: make update

      - name: Build Goo Engine (Windows)
        run: make -j %NUMBER_OF_PROCESSORS%

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: goo-engine-windows
          path: build_windows/bin/Release/blender.exe