name: Build Goo Engine (Windows)

on:
  workflow_dispatch:
  push:
    branches:
      - goo-engine-v3.6-release

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Goo Engine
        uses: actions/checkout@v3
        with:
          ref: goo-engine-v3.6-release

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        shell: cmd
        run: |
          choco install -y cmake ninja git 7zip svn subversion

      - name: Verify tools
        shell: cmd
        run: |
          python --version
          svn --version

      - name: Update libraries
        shell: cmd
        run: |
          call make.bat update

      - name: Build Goo Engine
        shell: cmd
        run: |
          call make.bat -j %NUMBER_OF_PROCESSORS%

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: GooEngine-Windows
          path: build_windows/bin/Release/**